server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接 https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
weixin:
  config:
    originalid: gh_59b7f1855bde
    token: mikasa
    app-id: wx2846d06252d4ec16
    app-secret: 3859408585a2a91d014a6bd5e12dc9c1
    template_id: OaccpGQh8mp3RYw3iqfEw7vkb7V04S4cJ9ZyEEzPcEM


spring:
  datasource:
    username: root
    password: wj515253
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: mika.pro.domain.po

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000143684315
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC/QzCazZUjcQX/3C4GgziHg/FCfm/3EO5WSeIz7ujPG3fKITphLi3pJycwyt9avZYssq1yA2tEsilX+D7c+c+9ftEdIknN7/5qMQsn6vTsiGekkxaXtlC6LP3LiQu71NqXwrFQhoitobcPYVPdSodxjsUjcitF/yyN2lgbIGd5Ifpgzt8g8RQ2Dqa0j0YDqGyGHm8cYHo7s0HxjUob7sNyx//ieBDgQTSXGAqCt4ZXoMq/CIWpkKvJ0q3T8/eXlUcnLKtbs1b2DvQ4p9cHC9xB4WzncnY6l+xXlDlE4oFhwqFKQgBjbvu9cvvuINtNAT59huzXOhbPUBBpP9ZW83VfAgMBAAECggEBAKEFqTr7D69Z7UoejaUv/nygyZJIrmzcFTwSUd2VKu2KW4yR8vt0DHT5YJZEhkx3xqH0/+84D6wzLnmAZzRVIN+Rj+4uOuKlRZUTmyfNOMyWfmNg7ill9Yr4a+dahsVpC2uvHucDjLhZqKvLLfblUyh4oWIZMXNpxJHcnEaiPlsMma7/u27FOBqoKfVT9cLJGWG2yWWFgjszhoH9ZwNe7lJwQxhjBNFkw+8c6QUYI/ZZ+XzWg41PK6fS0nSxVfgwc9ykN3P+KIHrzplJJ4/r1FVshBQlsqHuDX2TlMJnwSF6WrPV7OxjJRgsjooe7umggNRDyryzY7i5zsCPwhPPoAkCgYEA7P18uCdjYz/G9fRGHZQJrWKdsUDAkvudBvTPnwcRC/Em58NvkN2coXacxwJCCLFF3a+REU8bAi0fMNvVzbub6n4rEQr0ITHDroRUzZr+uXACteG0us2SEEZUVknzuiKsQ7CkWHU6FXfCYlKemRK6sySv8nH56McL8KtebCmZGNsCgYEAzpqzDVZyvBWL2cKG9G4MQQaPJJvuHNYnBxyzO8BAKRdWoxy3qQA6O+ioBxZQW76hfRNTsHLaLKAskj6vbDlq1j2YTXAZh8UZkrqfJzRZUe+E1dr30F8fobW9IaGZwaZX7fdMprCyXJNvh0XEoXFR7HCwo7s63FRvWcKvWmnGCs0CgYEAw+ZuWFPG5l3r+5gm9YBP15FzRPh/t4BiN0Pa9FwFDVgUjvSQnrFyLk48Ho2RRFo1pKDiS+qWKuBdrieqvtvccKRGuVnSoDXgybv91c/PzD35H5wpp1kS6n0YbhPHcxACUhoMYErW7rQGbPxaubIvvrIO91yb9n3DMviVntdsBI0CgYEAoQAe7hLjAD0OKZkUz9/+PqIc5Ft7GA+uhDVSWwq7NQpR4nRbjyB1QQBSCIvT/Vq1v6FTA1rNOB9t/F1LGNw5rFB9okLsMkhfYF977PI3dMlhS8ICgefO35afl1i2WBkHxpKDshZaOBhQviqZS3HidI1wqXcbLF3EFD/JpHxu7zUCgYBlZKP3DbVwCNXE7dliRKh1DwDLtOtWaHFgcFmYjxP3hdlSrbRXGxRvl4i2Pz8Zhltga+bqF5cHdh8lOCzI0sgNHAQ9nzo/IdCliqyHRQHU5OVqPgtgMa6vHRtph+uhKuryD2KevS8Zo5VAuRq0F0h8gAHL+1p/7eLb9k8xdVr+jw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0TBzjh3MnciQTAJGsqRS/Bamd0NeE8Ky0UB5ju0CcuzjxGnKubMTs70xRZgsKu75/wbD2X3t9HXxvGnexiphjwtV98k6FPS1AKMHILQTuZGo+MXYntWaIWpYnLQ8s9/WJGzsj/6wBA6dtGE0jIOyQyJovqVQQpF3+0FxN83KxWhY9QbaHMl0M7xZp59rCm6brG6ZxFa5XP+KpW02qQh+lA0wjJHuBqIldEaE1rCt7HlFVbEQEKj8qOg0FugNEJjfEDmdpV6IA8V91telwAbqNjZ4G5tDbvLbQjh4s9GpJNunzIaxWY4y1PH9wUMvQjLv8ZYOYLtGQ8pVE31bMOBnjwIDAQAB
  notify_url: http://mikasa.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign_type: RSA2
  charset: utf-8
  format: json

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
